// Generated by gencpp from file arm_follow/PersonKeypoints.msg
// DO NOT EDIT!


#ifndef ARM_FOLLOW_MESSAGE_PERSONKEYPOINTS_H
#define ARM_FOLLOW_MESSAGE_PERSONKEYPOINTS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace arm_follow
{
template <class ContainerAllocator>
struct PersonKeypoints_
{
  typedef PersonKeypoints_<ContainerAllocator> Type;

  PersonKeypoints_()
    : header()
    , person_id(0)
    , bbox_x(0.0)
    , bbox_y(0.0)
    , bbox_width(0.0)
    , bbox_height(0.0)
    , bbox_area(0.0)
    , bbox_confidence(0.0)
    , right_wrist_x(0.0)
    , right_wrist_y(0.0)
    , right_wrist_conf(0.0)
    , right_elbow_x(0.0)
    , right_elbow_y(0.0)
    , right_elbow_conf(0.0)
    , right_shoulder_x(0.0)
    , right_shoulder_y(0.0)
    , right_shoulder_conf(0.0)
    , image_width(0)
    , image_height(0)  {
    }
  PersonKeypoints_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , person_id(0)
    , bbox_x(0.0)
    , bbox_y(0.0)
    , bbox_width(0.0)
    , bbox_height(0.0)
    , bbox_area(0.0)
    , bbox_confidence(0.0)
    , right_wrist_x(0.0)
    , right_wrist_y(0.0)
    , right_wrist_conf(0.0)
    , right_elbow_x(0.0)
    , right_elbow_y(0.0)
    , right_elbow_conf(0.0)
    , right_shoulder_x(0.0)
    , right_shoulder_y(0.0)
    , right_shoulder_conf(0.0)
    , image_width(0)
    , image_height(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint32_t _person_id_type;
  _person_id_type person_id;

   typedef float _bbox_x_type;
  _bbox_x_type bbox_x;

   typedef float _bbox_y_type;
  _bbox_y_type bbox_y;

   typedef float _bbox_width_type;
  _bbox_width_type bbox_width;

   typedef float _bbox_height_type;
  _bbox_height_type bbox_height;

   typedef float _bbox_area_type;
  _bbox_area_type bbox_area;

   typedef float _bbox_confidence_type;
  _bbox_confidence_type bbox_confidence;

   typedef float _right_wrist_x_type;
  _right_wrist_x_type right_wrist_x;

   typedef float _right_wrist_y_type;
  _right_wrist_y_type right_wrist_y;

   typedef float _right_wrist_conf_type;
  _right_wrist_conf_type right_wrist_conf;

   typedef float _right_elbow_x_type;
  _right_elbow_x_type right_elbow_x;

   typedef float _right_elbow_y_type;
  _right_elbow_y_type right_elbow_y;

   typedef float _right_elbow_conf_type;
  _right_elbow_conf_type right_elbow_conf;

   typedef float _right_shoulder_x_type;
  _right_shoulder_x_type right_shoulder_x;

   typedef float _right_shoulder_y_type;
  _right_shoulder_y_type right_shoulder_y;

   typedef float _right_shoulder_conf_type;
  _right_shoulder_conf_type right_shoulder_conf;

   typedef uint32_t _image_width_type;
  _image_width_type image_width;

   typedef uint32_t _image_height_type;
  _image_height_type image_height;





  typedef boost::shared_ptr< ::arm_follow::PersonKeypoints_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arm_follow::PersonKeypoints_<ContainerAllocator> const> ConstPtr;

}; // struct PersonKeypoints_

typedef ::arm_follow::PersonKeypoints_<std::allocator<void> > PersonKeypoints;

typedef boost::shared_ptr< ::arm_follow::PersonKeypoints > PersonKeypointsPtr;
typedef boost::shared_ptr< ::arm_follow::PersonKeypoints const> PersonKeypointsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::arm_follow::PersonKeypoints_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::arm_follow::PersonKeypoints_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::arm_follow::PersonKeypoints_<ContainerAllocator1> & lhs, const ::arm_follow::PersonKeypoints_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.person_id == rhs.person_id &&
    lhs.bbox_x == rhs.bbox_x &&
    lhs.bbox_y == rhs.bbox_y &&
    lhs.bbox_width == rhs.bbox_width &&
    lhs.bbox_height == rhs.bbox_height &&
    lhs.bbox_area == rhs.bbox_area &&
    lhs.bbox_confidence == rhs.bbox_confidence &&
    lhs.right_wrist_x == rhs.right_wrist_x &&
    lhs.right_wrist_y == rhs.right_wrist_y &&
    lhs.right_wrist_conf == rhs.right_wrist_conf &&
    lhs.right_elbow_x == rhs.right_elbow_x &&
    lhs.right_elbow_y == rhs.right_elbow_y &&
    lhs.right_elbow_conf == rhs.right_elbow_conf &&
    lhs.right_shoulder_x == rhs.right_shoulder_x &&
    lhs.right_shoulder_y == rhs.right_shoulder_y &&
    lhs.right_shoulder_conf == rhs.right_shoulder_conf &&
    lhs.image_width == rhs.image_width &&
    lhs.image_height == rhs.image_height;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::arm_follow::PersonKeypoints_<ContainerAllocator1> & lhs, const ::arm_follow::PersonKeypoints_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace arm_follow

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::arm_follow::PersonKeypoints_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arm_follow::PersonKeypoints_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arm_follow::PersonKeypoints_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arm_follow::PersonKeypoints_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arm_follow::PersonKeypoints_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arm_follow::PersonKeypoints_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::arm_follow::PersonKeypoints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b8aef0b6f60577e67360824121ee7a78";
  }

  static const char* value(const ::arm_follow::PersonKeypoints_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb8aef0b6f60577e6ULL;
  static const uint64_t static_value2 = 0x7360824121ee7a78ULL;
};

template<class ContainerAllocator>
struct DataType< ::arm_follow::PersonKeypoints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "arm_follow/PersonKeypoints";
  }

  static const char* value(const ::arm_follow::PersonKeypoints_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::arm_follow::PersonKeypoints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# PersonKeypoints.msg\n"
"# 一个人体的关键点数据\n"
"\n"
"std_msgs/Header header\n"
"uint32 person_id          # 人员ID\n"
"float32 bbox_x            # 检测框左上角x\n"
"float32 bbox_y            # 检测框左上角y\n"
"float32 bbox_width        # 检测框宽度\n"
"float32 bbox_height       # 检测框高度\n"
"float32 bbox_area         # 检测框面积\n"
"float32 bbox_confidence   # 检测框置信度（YOLO显示的置信度）\n"
"\n"
"# 右手关键点（COCO格式中通常是右手腕，索引10）\n"
"float32 right_wrist_x     # 右手腕x坐标\n"
"float32 right_wrist_y     # 右手腕y坐标\n"
"float32 right_wrist_conf  # 右手腕置信度\n"
"\n"
"# 右手肘（索引8）\n"
"float32 right_elbow_x\n"
"float32 right_elbow_y\n"
"float32 right_elbow_conf\n"
"\n"
"# 右肩膀（用于判断右手是否伸出）\n"
"float32 right_shoulder_x\n"
"float32 right_shoulder_y\n"
"float32 right_shoulder_conf\n"
"\n"
"# 图像尺寸（用于计算角度）\n"
"uint32 image_width\n"
"uint32 image_height\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::arm_follow::PersonKeypoints_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::arm_follow::PersonKeypoints_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.person_id);
      stream.next(m.bbox_x);
      stream.next(m.bbox_y);
      stream.next(m.bbox_width);
      stream.next(m.bbox_height);
      stream.next(m.bbox_area);
      stream.next(m.bbox_confidence);
      stream.next(m.right_wrist_x);
      stream.next(m.right_wrist_y);
      stream.next(m.right_wrist_conf);
      stream.next(m.right_elbow_x);
      stream.next(m.right_elbow_y);
      stream.next(m.right_elbow_conf);
      stream.next(m.right_shoulder_x);
      stream.next(m.right_shoulder_y);
      stream.next(m.right_shoulder_conf);
      stream.next(m.image_width);
      stream.next(m.image_height);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PersonKeypoints_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::arm_follow::PersonKeypoints_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::arm_follow::PersonKeypoints_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "person_id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.person_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "bbox_x: ";
    Printer<float>::stream(s, indent + "  ", v.bbox_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "bbox_y: ";
    Printer<float>::stream(s, indent + "  ", v.bbox_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "bbox_width: ";
    Printer<float>::stream(s, indent + "  ", v.bbox_width);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "bbox_height: ";
    Printer<float>::stream(s, indent + "  ", v.bbox_height);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "bbox_area: ";
    Printer<float>::stream(s, indent + "  ", v.bbox_area);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "bbox_confidence: ";
    Printer<float>::stream(s, indent + "  ", v.bbox_confidence);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "right_wrist_x: ";
    Printer<float>::stream(s, indent + "  ", v.right_wrist_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "right_wrist_y: ";
    Printer<float>::stream(s, indent + "  ", v.right_wrist_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "right_wrist_conf: ";
    Printer<float>::stream(s, indent + "  ", v.right_wrist_conf);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "right_elbow_x: ";
    Printer<float>::stream(s, indent + "  ", v.right_elbow_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "right_elbow_y: ";
    Printer<float>::stream(s, indent + "  ", v.right_elbow_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "right_elbow_conf: ";
    Printer<float>::stream(s, indent + "  ", v.right_elbow_conf);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "right_shoulder_x: ";
    Printer<float>::stream(s, indent + "  ", v.right_shoulder_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "right_shoulder_y: ";
    Printer<float>::stream(s, indent + "  ", v.right_shoulder_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "right_shoulder_conf: ";
    Printer<float>::stream(s, indent + "  ", v.right_shoulder_conf);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "image_width: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.image_width);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "image_height: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.image_height);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARM_FOLLOW_MESSAGE_PERSONKEYPOINTS_H
