// Generated by gencpp from file arm_follow/PersonsKeypoints.msg
// DO NOT EDIT!


#ifndef ARM_FOLLOW_MESSAGE_PERSONSKEYPOINTS_H
#define ARM_FOLLOW_MESSAGE_PERSONSKEYPOINTS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <arm_follow/PersonKeypoints.h>

namespace arm_follow
{
template <class ContainerAllocator>
struct PersonsKeypoints_
{
  typedef PersonsKeypoints_<ContainerAllocator> Type;

  PersonsKeypoints_()
    : header()
    , persons()  {
    }
  PersonsKeypoints_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , persons(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::arm_follow::PersonKeypoints_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::arm_follow::PersonKeypoints_<ContainerAllocator> >> _persons_type;
  _persons_type persons;





  typedef boost::shared_ptr< ::arm_follow::PersonsKeypoints_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arm_follow::PersonsKeypoints_<ContainerAllocator> const> ConstPtr;

}; // struct PersonsKeypoints_

typedef ::arm_follow::PersonsKeypoints_<std::allocator<void> > PersonsKeypoints;

typedef boost::shared_ptr< ::arm_follow::PersonsKeypoints > PersonsKeypointsPtr;
typedef boost::shared_ptr< ::arm_follow::PersonsKeypoints const> PersonsKeypointsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::arm_follow::PersonsKeypoints_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::arm_follow::PersonsKeypoints_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::arm_follow::PersonsKeypoints_<ContainerAllocator1> & lhs, const ::arm_follow::PersonsKeypoints_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.persons == rhs.persons;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::arm_follow::PersonsKeypoints_<ContainerAllocator1> & lhs, const ::arm_follow::PersonsKeypoints_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace arm_follow

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::arm_follow::PersonsKeypoints_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arm_follow::PersonsKeypoints_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arm_follow::PersonsKeypoints_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arm_follow::PersonsKeypoints_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arm_follow::PersonsKeypoints_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arm_follow::PersonsKeypoints_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::arm_follow::PersonsKeypoints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2cc6b7f8f80dc708d5b607449f5f648f";
  }

  static const char* value(const ::arm_follow::PersonsKeypoints_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2cc6b7f8f80dc708ULL;
  static const uint64_t static_value2 = 0xd5b607449f5f648fULL;
};

template<class ContainerAllocator>
struct DataType< ::arm_follow::PersonsKeypoints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "arm_follow/PersonsKeypoints";
  }

  static const char* value(const ::arm_follow::PersonsKeypoints_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::arm_follow::PersonsKeypoints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# PersonsKeypoints.msg\n"
"# 多个人体的关键点数据列表\n"
"\n"
"std_msgs/Header header\n"
"PersonKeypoints[] persons  # 所有人体的关键点列表\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: arm_follow/PersonKeypoints\n"
"# PersonKeypoints.msg\n"
"# 一个人体的关键点数据\n"
"\n"
"std_msgs/Header header\n"
"uint32 person_id          # 人员ID\n"
"float32 bbox_x            # 检测框左上角x\n"
"float32 bbox_y            # 检测框左上角y\n"
"float32 bbox_width        # 检测框宽度\n"
"float32 bbox_height       # 检测框高度\n"
"float32 bbox_area         # 检测框面积\n"
"float32 bbox_confidence   # 检测框置信度（YOLO显示的置信度）\n"
"\n"
"# 右手关键点（COCO格式中通常是右手腕，索引10）\n"
"float32 right_wrist_x     # 右手腕x坐标\n"
"float32 right_wrist_y     # 右手腕y坐标\n"
"float32 right_wrist_conf  # 右手腕置信度\n"
"\n"
"# 右手肘（索引8）\n"
"float32 right_elbow_x\n"
"float32 right_elbow_y\n"
"float32 right_elbow_conf\n"
"\n"
"# 右肩膀（用于判断右手是否伸出）\n"
"float32 right_shoulder_x\n"
"float32 right_shoulder_y\n"
"float32 right_shoulder_conf\n"
"\n"
"# 图像尺寸（用于计算角度）\n"
"uint32 image_width\n"
"uint32 image_height\n"
"\n"
;
  }

  static const char* value(const ::arm_follow::PersonsKeypoints_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::arm_follow::PersonsKeypoints_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.persons);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PersonsKeypoints_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::arm_follow::PersonsKeypoints_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::arm_follow::PersonsKeypoints_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "persons: ";
    if (v.persons.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.persons.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::arm_follow::PersonKeypoints_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.persons[i]);
    }
    if (v.persons.empty() || false)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARM_FOLLOW_MESSAGE_PERSONSKEYPOINTS_H
