# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from my_car_yolo/ImuProcessed.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class ImuProcessed(genpy.Message):
  _md5sum = "f8eb09331f7dc4e2c7e0240f0df9da14"
  _type = "my_car_yolo/ImuProcessed"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """# ImuProcessed.msg
# 处理后的IMU数据

std_msgs/Header header
float64 yaw                    # 航向角 (度，0-360，已处理360°跳变)
float64 yaw_filtered           # 滤波后的航向角
float64 yaw_rate               # 角速度 (rad/s)
float64 gyro_bias_x            # X轴陀螺仪零偏
float64 gyro_bias_y            # Y轴陀螺仪零偏
float64 gyro_bias_z            # Z轴陀螺仪零偏
float64 accel_x                # X轴加速度 (m/s²)
float64 accel_y                # Y轴加速度 (m/s²)
float64 accel_z                # Z轴加速度 (m/s²)

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id
"""
  __slots__ = ['header','yaw','yaw_filtered','yaw_rate','gyro_bias_x','gyro_bias_y','gyro_bias_z','accel_x','accel_y','accel_z']
  _slot_types = ['std_msgs/Header','float64','float64','float64','float64','float64','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,yaw,yaw_filtered,yaw_rate,gyro_bias_x,gyro_bias_y,gyro_bias_z,accel_x,accel_y,accel_z

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ImuProcessed, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.yaw is None:
        self.yaw = 0.
      if self.yaw_filtered is None:
        self.yaw_filtered = 0.
      if self.yaw_rate is None:
        self.yaw_rate = 0.
      if self.gyro_bias_x is None:
        self.gyro_bias_x = 0.
      if self.gyro_bias_y is None:
        self.gyro_bias_y = 0.
      if self.gyro_bias_z is None:
        self.gyro_bias_z = 0.
      if self.accel_x is None:
        self.accel_x = 0.
      if self.accel_y is None:
        self.accel_y = 0.
      if self.accel_z is None:
        self.accel_z = 0.
    else:
      self.header = std_msgs.msg.Header()
      self.yaw = 0.
      self.yaw_filtered = 0.
      self.yaw_rate = 0.
      self.gyro_bias_x = 0.
      self.gyro_bias_y = 0.
      self.gyro_bias_z = 0.
      self.accel_x = 0.
      self.accel_y = 0.
      self.accel_z = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_9d().pack(_x.yaw, _x.yaw_filtered, _x.yaw_rate, _x.gyro_bias_x, _x.gyro_bias_y, _x.gyro_bias_z, _x.accel_x, _x.accel_y, _x.accel_z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 72
      (_x.yaw, _x.yaw_filtered, _x.yaw_rate, _x.gyro_bias_x, _x.gyro_bias_y, _x.gyro_bias_z, _x.accel_x, _x.accel_y, _x.accel_z,) = _get_struct_9d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_9d().pack(_x.yaw, _x.yaw_filtered, _x.yaw_rate, _x.gyro_bias_x, _x.gyro_bias_y, _x.gyro_bias_z, _x.accel_x, _x.accel_y, _x.accel_z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 72
      (_x.yaw, _x.yaw_filtered, _x.yaw_rate, _x.gyro_bias_x, _x.gyro_bias_y, _x.gyro_bias_z, _x.accel_x, _x.accel_y, _x.accel_z,) = _get_struct_9d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_9d = None
def _get_struct_9d():
    global _struct_9d
    if _struct_9d is None:
        _struct_9d = struct.Struct("<9d")
    return _struct_9d
