# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from my_car_yolo/ObjectDetection.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class ObjectDetection(genpy.Message):
  _md5sum = "74b64be95b23c1ba8f1d1679b6ef3c59"
  _type = "my_car_yolo/ObjectDetection"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """# ObjectDetection.msg
# 单个物体的检测结果

std_msgs/Header header
uint32 object_id          # 物体ID (1, 2, 3...)
float32 center_x          # 中心点x坐标（像素）
float32 center_y          # 中心点y坐标（像素）
float32 confidence        # 检测置信度
float32 bbox_x            # 边界框左上角x
float32 bbox_y            # 边界框左上角y
float32 bbox_width        # 边界框宽度
float32 bbox_height        # 边界框高度
uint32 image_width        # 图像宽度
uint32 image_height       # 图像高度

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id
"""
  __slots__ = ['header','object_id','center_x','center_y','confidence','bbox_x','bbox_y','bbox_width','bbox_height','image_width','image_height']
  _slot_types = ['std_msgs/Header','uint32','float32','float32','float32','float32','float32','float32','float32','uint32','uint32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,object_id,center_x,center_y,confidence,bbox_x,bbox_y,bbox_width,bbox_height,image_width,image_height

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ObjectDetection, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.object_id is None:
        self.object_id = 0
      if self.center_x is None:
        self.center_x = 0.
      if self.center_y is None:
        self.center_y = 0.
      if self.confidence is None:
        self.confidence = 0.
      if self.bbox_x is None:
        self.bbox_x = 0.
      if self.bbox_y is None:
        self.bbox_y = 0.
      if self.bbox_width is None:
        self.bbox_width = 0.
      if self.bbox_height is None:
        self.bbox_height = 0.
      if self.image_width is None:
        self.image_width = 0
      if self.image_height is None:
        self.image_height = 0
    else:
      self.header = std_msgs.msg.Header()
      self.object_id = 0
      self.center_x = 0.
      self.center_y = 0.
      self.confidence = 0.
      self.bbox_x = 0.
      self.bbox_y = 0.
      self.bbox_width = 0.
      self.bbox_height = 0.
      self.image_width = 0
      self.image_height = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_I7f2I().pack(_x.object_id, _x.center_x, _x.center_y, _x.confidence, _x.bbox_x, _x.bbox_y, _x.bbox_width, _x.bbox_height, _x.image_width, _x.image_height))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 40
      (_x.object_id, _x.center_x, _x.center_y, _x.confidence, _x.bbox_x, _x.bbox_y, _x.bbox_width, _x.bbox_height, _x.image_width, _x.image_height,) = _get_struct_I7f2I().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_I7f2I().pack(_x.object_id, _x.center_x, _x.center_y, _x.confidence, _x.bbox_x, _x.bbox_y, _x.bbox_width, _x.bbox_height, _x.image_width, _x.image_height))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 40
      (_x.object_id, _x.center_x, _x.center_y, _x.confidence, _x.bbox_x, _x.bbox_y, _x.bbox_width, _x.bbox_height, _x.image_width, _x.image_height,) = _get_struct_I7f2I().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_I7f2I = None
def _get_struct_I7f2I():
    global _struct_I7f2I
    if _struct_I7f2I is None:
        _struct_I7f2I = struct.Struct("<I7f2I")
    return _struct_I7f2I
