(cl:in-package my_car_yolo-msg)
(cl:export '(HEADER-VAL
          HEADER
          CHILD_FRAME_ID-VAL
          CHILD_FRAME_ID
          POSE-VAL
          POSE
          TWIST-VAL
          TWIST
          DISTANCE_LEFT-VAL
          DISTANCE_LEFT
          DISTANCE_RIGHT-VAL
          DISTANCE_RIGHT
          LINEAR_VELOCITY-VAL
          LINEAR_VELOCITY
          ANGULAR_VELOCITY-VAL
          ANGULAR_VELOCITY
          IMU_YAW-VAL
          IMU_YAW
          FUSED_YAW-VAL
          FUSED_YAW
          YAW_CONFIDENCE-VAL
          YAW_CONFIDENCE
          IS_SLIPPING-VAL
          IS_SLIPPING
          SLIP_RATIO-VAL
          SLIP_RATIO
          ENCODER_ERRORS-VAL
          ENCODER_ERRORS
))