(cl:in-package arm_follow-msg)
(cl:export '(HEADER-VAL
          HEADER
          PERSON_ID-VAL
          PERSON_ID
          BBOX_X-VAL
          BBOX_X
          BBOX_Y-VAL
          BBOX_Y
          BBOX_WIDTH-VAL
          BBOX_WIDTH
          BBOX_HEIGHT-VAL
          BBOX_HEIGHT
          BBOX_AREA-VAL
          BBOX_AREA
          BBOX_CONFIDENCE-VAL
          BBOX_CONFIDENCE
          RIGHT_WRIST_X-VAL
          RIGHT_WRIST_X
          RIGHT_WRIST_Y-VAL
          RIGHT_WRIST_Y
          RIGHT_WRIST_CONF-VAL
          RIGHT_WRIST_CONF
          RIGHT_ELBOW_X-VAL
          RIGHT_ELBOW_X
          RIGHT_ELBOW_Y-VAL
          RIGHT_ELBOW_Y
          RIGHT_ELBOW_CONF-VAL
          RIGHT_ELBOW_CONF
          RIGHT_SHOULDER_X-VAL
          RIGHT_SHOULDER_X
          RIGHT_SHOULDER_Y-VAL
          RIGHT_SHOULDER_Y
          RIGHT_SHOULDER_CONF-VAL
          RIGHT_SHOULDER_CONF
          IMAGE_WIDTH-VAL
          IMAGE_WIDTH
          IMAGE_HEIGHT-VAL
          IMAGE_HEIGHT
))