// Generated by gencpp from file intera_core_msgs/SolvePositionIKRequest.msg
// DO NOT EDIT!


#ifndef INTERA_CORE_MSGS_MESSAGE_SOLVEPOSITIONIKREQUEST_H
#define INTERA_CORE_MSGS_MESSAGE_SOLVEPOSITIONIKREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseStamped.h>
#include <sensor_msgs/JointState.h>
#include <sensor_msgs/JointState.h>

namespace intera_core_msgs
{
template <class ContainerAllocator>
struct SolvePositionIKRequest_
{
  typedef SolvePositionIKRequest_<ContainerAllocator> Type;

  SolvePositionIKRequest_()
    : pose_stamp()
    , seed_angles()
    , seed_mode(0)
    , use_nullspace_goal()
    , nullspace_goal()
    , nullspace_gain()
    , tip_names()  {
    }
  SolvePositionIKRequest_(const ContainerAllocator& _alloc)
    : pose_stamp(_alloc)
    , seed_angles(_alloc)
    , seed_mode(0)
    , use_nullspace_goal(_alloc)
    , nullspace_goal(_alloc)
    , nullspace_gain(_alloc)
    , tip_names(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::geometry_msgs::PoseStamped_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::PoseStamped_<ContainerAllocator> >> _pose_stamp_type;
  _pose_stamp_type pose_stamp;

   typedef std::vector< ::sensor_msgs::JointState_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::sensor_msgs::JointState_<ContainerAllocator> >> _seed_angles_type;
  _seed_angles_type seed_angles;

   typedef int8_t _seed_mode_type;
  _seed_mode_type seed_mode;

   typedef std::vector<uint8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint8_t>> _use_nullspace_goal_type;
  _use_nullspace_goal_type use_nullspace_goal;

   typedef std::vector< ::sensor_msgs::JointState_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::sensor_msgs::JointState_<ContainerAllocator> >> _nullspace_goal_type;
  _nullspace_goal_type nullspace_goal;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _nullspace_gain_type;
  _nullspace_gain_type nullspace_gain;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _tip_names_type;
  _tip_names_type tip_names;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(SEED_AUTO)
  #undef SEED_AUTO
#endif
#if defined(_WIN32) && defined(SEED_USER)
  #undef SEED_USER
#endif
#if defined(_WIN32) && defined(SEED_CURRENT)
  #undef SEED_CURRENT
#endif
#if defined(_WIN32) && defined(SEED_NS_MAP)
  #undef SEED_NS_MAP
#endif

  enum {
    SEED_AUTO = 0,
    SEED_USER = 1,
    SEED_CURRENT = 2,
    SEED_NS_MAP = 3,
  };


  typedef boost::shared_ptr< ::intera_core_msgs::SolvePositionIKRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::intera_core_msgs::SolvePositionIKRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SolvePositionIKRequest_

typedef ::intera_core_msgs::SolvePositionIKRequest_<std::allocator<void> > SolvePositionIKRequest;

typedef boost::shared_ptr< ::intera_core_msgs::SolvePositionIKRequest > SolvePositionIKRequestPtr;
typedef boost::shared_ptr< ::intera_core_msgs::SolvePositionIKRequest const> SolvePositionIKRequestConstPtr;

// constants requiring out of line definition

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::intera_core_msgs::SolvePositionIKRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::intera_core_msgs::SolvePositionIKRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::intera_core_msgs::SolvePositionIKRequest_<ContainerAllocator1> & lhs, const ::intera_core_msgs::SolvePositionIKRequest_<ContainerAllocator2> & rhs)
{
  return lhs.pose_stamp == rhs.pose_stamp &&
    lhs.seed_angles == rhs.seed_angles &&
    lhs.seed_mode == rhs.seed_mode &&
    lhs.use_nullspace_goal == rhs.use_nullspace_goal &&
    lhs.nullspace_goal == rhs.nullspace_goal &&
    lhs.nullspace_gain == rhs.nullspace_gain &&
    lhs.tip_names == rhs.tip_names;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::intera_core_msgs::SolvePositionIKRequest_<ContainerAllocator1> & lhs, const ::intera_core_msgs::SolvePositionIKRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace intera_core_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::intera_core_msgs::SolvePositionIKRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::intera_core_msgs::SolvePositionIKRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::intera_core_msgs::SolvePositionIKRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::intera_core_msgs::SolvePositionIKRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::intera_core_msgs::SolvePositionIKRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::intera_core_msgs::SolvePositionIKRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::intera_core_msgs::SolvePositionIKRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b09dd99695bb18639bfea7c92d0a89ca";
  }

  static const char* value(const ::intera_core_msgs::SolvePositionIKRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb09dd99695bb1863ULL;
  static const uint64_t static_value2 = 0x9bfea7c92d0a89caULL;
};

template<class ContainerAllocator>
struct DataType< ::intera_core_msgs::SolvePositionIKRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "intera_core_msgs/SolvePositionIKRequest";
  }

  static const char* value(const ::intera_core_msgs::SolvePositionIKRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::intera_core_msgs::SolvePositionIKRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Endpoint Pose(s) to request Inverse-Kinematics joint solutions for.\n"
"geometry_msgs/PoseStamped[] pose_stamp\n"
"\n"
"# (optional) Joint Angle Seed(s) for IK solver.\n"
"# * specify a JointState seed for each pose_stamp, using name[] and position[]\n"
"# * empty arrays or a non-default seed_mode will cause user seed to not be used\n"
"sensor_msgs/JointState[] seed_angles\n"
"\n"
"# Seed Type Mode\n"
"# * default (SEED_AUTO) mode: iterate through seed types until first valid\n"
"#                             solution is found\n"
"# * setting any other mode:   try only that seed type\n"
"int8 SEED_AUTO    = 0\n"
"int8 SEED_USER    = 1\n"
"int8 SEED_CURRENT = 2\n"
"int8 SEED_NS_MAP  = 3\n"
"\n"
"int8 seed_mode\n"
"\n"
"# For each IK request, tells whether it should use the nullspace goal\n"
"bool[] use_nullspace_goal\n"
"\n"
"# The nullspace goal can either be the full set or subset of joint angles\n"
"sensor_msgs/JointState[] nullspace_goal\n"
"\n"
"# The gain used to bias toward the nullspace goal. Must be [0.0, 1.0]\n"
"# If empty, the default gain of 0.4 will be used\n"
"float64[] nullspace_gain\n"
"\n"
"# Tip name for each pose IK\n"
"string[] tip_names\n"
"\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/JointState\n"
"# This is a message that holds data to describe the state of a set of torque controlled joints. \n"
"#\n"
"# The state of each joint (revolute or prismatic) is defined by:\n"
"#  * the position of the joint (rad or m),\n"
"#  * the velocity of the joint (rad/s or m/s) and \n"
"#  * the effort that is applied in the joint (Nm or N).\n"
"#\n"
"# Each joint is uniquely identified by its name\n"
"# The header specifies the time at which the joint states were recorded. All the joint states\n"
"# in one message have to be recorded at the same time.\n"
"#\n"
"# This message consists of a multiple arrays, one for each part of the joint state. \n"
"# The goal is to make each of the fields optional. When e.g. your joints have no\n"
"# effort associated with them, you can leave the effort array empty. \n"
"#\n"
"# All arrays in this message should have the same size, or be empty.\n"
"# This is the only way to uniquely associate the joint name with the correct\n"
"# states.\n"
"\n"
"\n"
"Header header\n"
"\n"
"string[] name\n"
"float64[] position\n"
"float64[] velocity\n"
"float64[] effort\n"
;
  }

  static const char* value(const ::intera_core_msgs::SolvePositionIKRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::intera_core_msgs::SolvePositionIKRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pose_stamp);
      stream.next(m.seed_angles);
      stream.next(m.seed_mode);
      stream.next(m.use_nullspace_goal);
      stream.next(m.nullspace_goal);
      stream.next(m.nullspace_gain);
      stream.next(m.tip_names);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SolvePositionIKRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::intera_core_msgs::SolvePositionIKRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::intera_core_msgs::SolvePositionIKRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "pose_stamp: ";
    if (v.pose_stamp.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.pose_stamp.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.pose_stamp[i]);
    }
    if (v.pose_stamp.empty() || false)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "seed_angles: ";
    if (v.seed_angles.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.seed_angles.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::sensor_msgs::JointState_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.seed_angles[i]);
    }
    if (v.seed_angles.empty() || false)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "seed_mode: ";
    Printer<int8_t>::stream(s, indent + "  ", v.seed_mode);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "use_nullspace_goal: ";
    if (v.use_nullspace_goal.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.use_nullspace_goal.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<uint8_t>::stream(s, true ? std::string() : indent + "    ", v.use_nullspace_goal[i]);
    }
    if (v.use_nullspace_goal.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "nullspace_goal: ";
    if (v.nullspace_goal.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.nullspace_goal.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::sensor_msgs::JointState_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.nullspace_goal[i]);
    }
    if (v.nullspace_goal.empty() || false)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "nullspace_gain: ";
    if (v.nullspace_gain.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.nullspace_gain.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.nullspace_gain[i]);
    }
    if (v.nullspace_gain.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "tip_names: ";
    if (v.tip_names.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.tip_names.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, true ? std::string() : indent + "    ", v.tip_names[i]);
    }
    if (v.tip_names.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // INTERA_CORE_MSGS_MESSAGE_SOLVEPOSITIONIKREQUEST_H
