// Generated by gencpp from file my_car_yolo/ImuProcessed.msg
// DO NOT EDIT!


#ifndef MY_CAR_YOLO_MESSAGE_IMUPROCESSED_H
#define MY_CAR_YOLO_MESSAGE_IMUPROCESSED_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace my_car_yolo
{
template <class ContainerAllocator>
struct ImuProcessed_
{
  typedef ImuProcessed_<ContainerAllocator> Type;

  ImuProcessed_()
    : header()
    , yaw(0.0)
    , yaw_filtered(0.0)
    , yaw_rate(0.0)
    , gyro_bias_x(0.0)
    , gyro_bias_y(0.0)
    , gyro_bias_z(0.0)
    , accel_x(0.0)
    , accel_y(0.0)
    , accel_z(0.0)  {
    }
  ImuProcessed_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , yaw(0.0)
    , yaw_filtered(0.0)
    , yaw_rate(0.0)
    , gyro_bias_x(0.0)
    , gyro_bias_y(0.0)
    , gyro_bias_z(0.0)
    , accel_x(0.0)
    , accel_y(0.0)
    , accel_z(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _yaw_type;
  _yaw_type yaw;

   typedef double _yaw_filtered_type;
  _yaw_filtered_type yaw_filtered;

   typedef double _yaw_rate_type;
  _yaw_rate_type yaw_rate;

   typedef double _gyro_bias_x_type;
  _gyro_bias_x_type gyro_bias_x;

   typedef double _gyro_bias_y_type;
  _gyro_bias_y_type gyro_bias_y;

   typedef double _gyro_bias_z_type;
  _gyro_bias_z_type gyro_bias_z;

   typedef double _accel_x_type;
  _accel_x_type accel_x;

   typedef double _accel_y_type;
  _accel_y_type accel_y;

   typedef double _accel_z_type;
  _accel_z_type accel_z;





  typedef boost::shared_ptr< ::my_car_yolo::ImuProcessed_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_car_yolo::ImuProcessed_<ContainerAllocator> const> ConstPtr;

}; // struct ImuProcessed_

typedef ::my_car_yolo::ImuProcessed_<std::allocator<void> > ImuProcessed;

typedef boost::shared_ptr< ::my_car_yolo::ImuProcessed > ImuProcessedPtr;
typedef boost::shared_ptr< ::my_car_yolo::ImuProcessed const> ImuProcessedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_car_yolo::ImuProcessed_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_car_yolo::ImuProcessed_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_car_yolo::ImuProcessed_<ContainerAllocator1> & lhs, const ::my_car_yolo::ImuProcessed_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.yaw == rhs.yaw &&
    lhs.yaw_filtered == rhs.yaw_filtered &&
    lhs.yaw_rate == rhs.yaw_rate &&
    lhs.gyro_bias_x == rhs.gyro_bias_x &&
    lhs.gyro_bias_y == rhs.gyro_bias_y &&
    lhs.gyro_bias_z == rhs.gyro_bias_z &&
    lhs.accel_x == rhs.accel_x &&
    lhs.accel_y == rhs.accel_y &&
    lhs.accel_z == rhs.accel_z;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_car_yolo::ImuProcessed_<ContainerAllocator1> & lhs, const ::my_car_yolo::ImuProcessed_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_car_yolo

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::my_car_yolo::ImuProcessed_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_car_yolo::ImuProcessed_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_car_yolo::ImuProcessed_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_car_yolo::ImuProcessed_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_car_yolo::ImuProcessed_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_car_yolo::ImuProcessed_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_car_yolo::ImuProcessed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f8eb09331f7dc4e2c7e0240f0df9da14";
  }

  static const char* value(const ::my_car_yolo::ImuProcessed_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf8eb09331f7dc4e2ULL;
  static const uint64_t static_value2 = 0xc7e0240f0df9da14ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_car_yolo::ImuProcessed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_car_yolo/ImuProcessed";
  }

  static const char* value(const ::my_car_yolo::ImuProcessed_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_car_yolo::ImuProcessed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ImuProcessed.msg\n"
"# 处理后的IMU数据\n"
"\n"
"std_msgs/Header header\n"
"float64 yaw                    # 航向角 (度，0-360，已处理360°跳变)\n"
"float64 yaw_filtered           # 滤波后的航向角\n"
"float64 yaw_rate               # 角速度 (rad/s)\n"
"float64 gyro_bias_x            # X轴陀螺仪零偏\n"
"float64 gyro_bias_y            # Y轴陀螺仪零偏\n"
"float64 gyro_bias_z            # Z轴陀螺仪零偏\n"
"float64 accel_x                # X轴加速度 (m/s²)\n"
"float64 accel_y                # Y轴加速度 (m/s²)\n"
"float64 accel_z                # Z轴加速度 (m/s²)\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::my_car_yolo::ImuProcessed_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_car_yolo::ImuProcessed_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.yaw);
      stream.next(m.yaw_filtered);
      stream.next(m.yaw_rate);
      stream.next(m.gyro_bias_x);
      stream.next(m.gyro_bias_y);
      stream.next(m.gyro_bias_z);
      stream.next(m.accel_x);
      stream.next(m.accel_y);
      stream.next(m.accel_z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ImuProcessed_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_car_yolo::ImuProcessed_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_car_yolo::ImuProcessed_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "yaw: ";
    Printer<double>::stream(s, indent + "  ", v.yaw);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "yaw_filtered: ";
    Printer<double>::stream(s, indent + "  ", v.yaw_filtered);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "yaw_rate: ";
    Printer<double>::stream(s, indent + "  ", v.yaw_rate);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "gyro_bias_x: ";
    Printer<double>::stream(s, indent + "  ", v.gyro_bias_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "gyro_bias_y: ";
    Printer<double>::stream(s, indent + "  ", v.gyro_bias_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "gyro_bias_z: ";
    Printer<double>::stream(s, indent + "  ", v.gyro_bias_z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "accel_x: ";
    Printer<double>::stream(s, indent + "  ", v.accel_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "accel_y: ";
    Printer<double>::stream(s, indent + "  ", v.accel_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "accel_z: ";
    Printer<double>::stream(s, indent + "  ", v.accel_z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_CAR_YOLO_MESSAGE_IMUPROCESSED_H
