// Generated by gencpp from file my_car_yolo/ObjectDetections.msg
// DO NOT EDIT!


#ifndef MY_CAR_YOLO_MESSAGE_OBJECTDETECTIONS_H
#define MY_CAR_YOLO_MESSAGE_OBJECTDETECTIONS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <my_car_yolo/ObjectDetection.h>

namespace my_car_yolo
{
template <class ContainerAllocator>
struct ObjectDetections_
{
  typedef ObjectDetections_<ContainerAllocator> Type;

  ObjectDetections_()
    : header()
    , objects()  {
    }
  ObjectDetections_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , objects(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::my_car_yolo::ObjectDetection_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::my_car_yolo::ObjectDetection_<ContainerAllocator> >> _objects_type;
  _objects_type objects;





  typedef boost::shared_ptr< ::my_car_yolo::ObjectDetections_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_car_yolo::ObjectDetections_<ContainerAllocator> const> ConstPtr;

}; // struct ObjectDetections_

typedef ::my_car_yolo::ObjectDetections_<std::allocator<void> > ObjectDetections;

typedef boost::shared_ptr< ::my_car_yolo::ObjectDetections > ObjectDetectionsPtr;
typedef boost::shared_ptr< ::my_car_yolo::ObjectDetections const> ObjectDetectionsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_car_yolo::ObjectDetections_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_car_yolo::ObjectDetections_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_car_yolo::ObjectDetections_<ContainerAllocator1> & lhs, const ::my_car_yolo::ObjectDetections_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.objects == rhs.objects;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_car_yolo::ObjectDetections_<ContainerAllocator1> & lhs, const ::my_car_yolo::ObjectDetections_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_car_yolo

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::my_car_yolo::ObjectDetections_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_car_yolo::ObjectDetections_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_car_yolo::ObjectDetections_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_car_yolo::ObjectDetections_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_car_yolo::ObjectDetections_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_car_yolo::ObjectDetections_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_car_yolo::ObjectDetections_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4612b7e38ebc3d1f73882710c9d084e0";
  }

  static const char* value(const ::my_car_yolo::ObjectDetections_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4612b7e38ebc3d1fULL;
  static const uint64_t static_value2 = 0x73882710c9d084e0ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_car_yolo::ObjectDetections_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_car_yolo/ObjectDetections";
  }

  static const char* value(const ::my_car_yolo::ObjectDetections_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_car_yolo::ObjectDetections_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ObjectDetections.msg\n"
"# 多个物体的检测结果列表\n"
"\n"
"std_msgs/Header header\n"
"ObjectDetection[] objects  # 所有检测到的物体列表\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: my_car_yolo/ObjectDetection\n"
"# ObjectDetection.msg\n"
"# 单个物体的检测结果\n"
"\n"
"std_msgs/Header header\n"
"uint32 object_id          # 物体ID (1, 2, 3...)\n"
"float32 center_x          # 中心点x坐标（像素）\n"
"float32 center_y          # 中心点y坐标（像素）\n"
"float32 confidence        # 检测置信度\n"
"float32 bbox_x            # 边界框左上角x\n"
"float32 bbox_y            # 边界框左上角y\n"
"float32 bbox_width        # 边界框宽度\n"
"float32 bbox_height        # 边界框高度\n"
"uint32 image_width        # 图像宽度\n"
"uint32 image_height       # 图像高度\n"
;
  }

  static const char* value(const ::my_car_yolo::ObjectDetections_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_car_yolo::ObjectDetections_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.objects);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObjectDetections_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_car_yolo::ObjectDetections_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_car_yolo::ObjectDetections_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "objects: ";
    if (v.objects.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.objects.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::my_car_yolo::ObjectDetection_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.objects[i]);
    }
    if (v.objects.empty() || false)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_CAR_YOLO_MESSAGE_OBJECTDETECTIONS_H
