// Generated by gencpp from file my_car_yolo/ObjectDetection.msg
// DO NOT EDIT!


#ifndef MY_CAR_YOLO_MESSAGE_OBJECTDETECTION_H
#define MY_CAR_YOLO_MESSAGE_OBJECTDETECTION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace my_car_yolo
{
template <class ContainerAllocator>
struct ObjectDetection_
{
  typedef ObjectDetection_<ContainerAllocator> Type;

  ObjectDetection_()
    : header()
    , object_id(0)
    , center_x(0.0)
    , center_y(0.0)
    , confidence(0.0)
    , bbox_x(0.0)
    , bbox_y(0.0)
    , bbox_width(0.0)
    , bbox_height(0.0)
    , image_width(0)
    , image_height(0)  {
    }
  ObjectDetection_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , object_id(0)
    , center_x(0.0)
    , center_y(0.0)
    , confidence(0.0)
    , bbox_x(0.0)
    , bbox_y(0.0)
    , bbox_width(0.0)
    , bbox_height(0.0)
    , image_width(0)
    , image_height(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint32_t _object_id_type;
  _object_id_type object_id;

   typedef float _center_x_type;
  _center_x_type center_x;

   typedef float _center_y_type;
  _center_y_type center_y;

   typedef float _confidence_type;
  _confidence_type confidence;

   typedef float _bbox_x_type;
  _bbox_x_type bbox_x;

   typedef float _bbox_y_type;
  _bbox_y_type bbox_y;

   typedef float _bbox_width_type;
  _bbox_width_type bbox_width;

   typedef float _bbox_height_type;
  _bbox_height_type bbox_height;

   typedef uint32_t _image_width_type;
  _image_width_type image_width;

   typedef uint32_t _image_height_type;
  _image_height_type image_height;





  typedef boost::shared_ptr< ::my_car_yolo::ObjectDetection_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_car_yolo::ObjectDetection_<ContainerAllocator> const> ConstPtr;

}; // struct ObjectDetection_

typedef ::my_car_yolo::ObjectDetection_<std::allocator<void> > ObjectDetection;

typedef boost::shared_ptr< ::my_car_yolo::ObjectDetection > ObjectDetectionPtr;
typedef boost::shared_ptr< ::my_car_yolo::ObjectDetection const> ObjectDetectionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_car_yolo::ObjectDetection_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_car_yolo::ObjectDetection_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_car_yolo::ObjectDetection_<ContainerAllocator1> & lhs, const ::my_car_yolo::ObjectDetection_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.object_id == rhs.object_id &&
    lhs.center_x == rhs.center_x &&
    lhs.center_y == rhs.center_y &&
    lhs.confidence == rhs.confidence &&
    lhs.bbox_x == rhs.bbox_x &&
    lhs.bbox_y == rhs.bbox_y &&
    lhs.bbox_width == rhs.bbox_width &&
    lhs.bbox_height == rhs.bbox_height &&
    lhs.image_width == rhs.image_width &&
    lhs.image_height == rhs.image_height;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_car_yolo::ObjectDetection_<ContainerAllocator1> & lhs, const ::my_car_yolo::ObjectDetection_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_car_yolo

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::my_car_yolo::ObjectDetection_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_car_yolo::ObjectDetection_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_car_yolo::ObjectDetection_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_car_yolo::ObjectDetection_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_car_yolo::ObjectDetection_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_car_yolo::ObjectDetection_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_car_yolo::ObjectDetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "74b64be95b23c1ba8f1d1679b6ef3c59";
  }

  static const char* value(const ::my_car_yolo::ObjectDetection_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x74b64be95b23c1baULL;
  static const uint64_t static_value2 = 0x8f1d1679b6ef3c59ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_car_yolo::ObjectDetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_car_yolo/ObjectDetection";
  }

  static const char* value(const ::my_car_yolo::ObjectDetection_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_car_yolo::ObjectDetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ObjectDetection.msg\n"
"# 单个物体的检测结果\n"
"\n"
"std_msgs/Header header\n"
"uint32 object_id          # 物体ID (1, 2, 3...)\n"
"float32 center_x          # 中心点x坐标（像素）\n"
"float32 center_y          # 中心点y坐标（像素）\n"
"float32 confidence        # 检测置信度\n"
"float32 bbox_x            # 边界框左上角x\n"
"float32 bbox_y            # 边界框左上角y\n"
"float32 bbox_width        # 边界框宽度\n"
"float32 bbox_height        # 边界框高度\n"
"uint32 image_width        # 图像宽度\n"
"uint32 image_height       # 图像高度\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::my_car_yolo::ObjectDetection_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_car_yolo::ObjectDetection_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.object_id);
      stream.next(m.center_x);
      stream.next(m.center_y);
      stream.next(m.confidence);
      stream.next(m.bbox_x);
      stream.next(m.bbox_y);
      stream.next(m.bbox_width);
      stream.next(m.bbox_height);
      stream.next(m.image_width);
      stream.next(m.image_height);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObjectDetection_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_car_yolo::ObjectDetection_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_car_yolo::ObjectDetection_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "object_id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.object_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "center_x: ";
    Printer<float>::stream(s, indent + "  ", v.center_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "center_y: ";
    Printer<float>::stream(s, indent + "  ", v.center_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "confidence: ";
    Printer<float>::stream(s, indent + "  ", v.confidence);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "bbox_x: ";
    Printer<float>::stream(s, indent + "  ", v.bbox_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "bbox_y: ";
    Printer<float>::stream(s, indent + "  ", v.bbox_y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "bbox_width: ";
    Printer<float>::stream(s, indent + "  ", v.bbox_width);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "bbox_height: ";
    Printer<float>::stream(s, indent + "  ", v.bbox_height);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "image_width: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.image_width);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "image_height: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.image_height);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_CAR_YOLO_MESSAGE_OBJECTDETECTION_H
