// Generated by gencpp from file my_car_yolo/OdometryProcessed.msg
// DO NOT EDIT!


#ifndef MY_CAR_YOLO_MESSAGE_ODOMETRYPROCESSED_H
#define MY_CAR_YOLO_MESSAGE_ODOMETRYPROCESSED_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/PoseWithCovariance.h>
#include <geometry_msgs/TwistWithCovariance.h>

namespace my_car_yolo
{
template <class ContainerAllocator>
struct OdometryProcessed_
{
  typedef OdometryProcessed_<ContainerAllocator> Type;

  OdometryProcessed_()
    : header()
    , child_frame_id()
    , pose()
    , twist()
    , distance_left(0.0)
    , distance_right(0.0)
    , linear_velocity(0.0)
    , angular_velocity(0.0)
    , imu_yaw(0.0)
    , fused_yaw(0.0)
    , yaw_confidence(0.0)
    , is_slipping(false)
    , slip_ratio(0.0)
    , encoder_errors(0)  {
    }
  OdometryProcessed_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , child_frame_id(_alloc)
    , pose(_alloc)
    , twist(_alloc)
    , distance_left(0.0)
    , distance_right(0.0)
    , linear_velocity(0.0)
    , angular_velocity(0.0)
    , imu_yaw(0.0)
    , fused_yaw(0.0)
    , yaw_confidence(0.0)
    , is_slipping(false)
    , slip_ratio(0.0)
    , encoder_errors(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _child_frame_id_type;
  _child_frame_id_type child_frame_id;

   typedef  ::geometry_msgs::PoseWithCovariance_<ContainerAllocator>  _pose_type;
  _pose_type pose;

   typedef  ::geometry_msgs::TwistWithCovariance_<ContainerAllocator>  _twist_type;
  _twist_type twist;

   typedef double _distance_left_type;
  _distance_left_type distance_left;

   typedef double _distance_right_type;
  _distance_right_type distance_right;

   typedef double _linear_velocity_type;
  _linear_velocity_type linear_velocity;

   typedef double _angular_velocity_type;
  _angular_velocity_type angular_velocity;

   typedef double _imu_yaw_type;
  _imu_yaw_type imu_yaw;

   typedef double _fused_yaw_type;
  _fused_yaw_type fused_yaw;

   typedef double _yaw_confidence_type;
  _yaw_confidence_type yaw_confidence;

   typedef uint8_t _is_slipping_type;
  _is_slipping_type is_slipping;

   typedef double _slip_ratio_type;
  _slip_ratio_type slip_ratio;

   typedef uint32_t _encoder_errors_type;
  _encoder_errors_type encoder_errors;





  typedef boost::shared_ptr< ::my_car_yolo::OdometryProcessed_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_car_yolo::OdometryProcessed_<ContainerAllocator> const> ConstPtr;

}; // struct OdometryProcessed_

typedef ::my_car_yolo::OdometryProcessed_<std::allocator<void> > OdometryProcessed;

typedef boost::shared_ptr< ::my_car_yolo::OdometryProcessed > OdometryProcessedPtr;
typedef boost::shared_ptr< ::my_car_yolo::OdometryProcessed const> OdometryProcessedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_car_yolo::OdometryProcessed_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_car_yolo::OdometryProcessed_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_car_yolo::OdometryProcessed_<ContainerAllocator1> & lhs, const ::my_car_yolo::OdometryProcessed_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.child_frame_id == rhs.child_frame_id &&
    lhs.pose == rhs.pose &&
    lhs.twist == rhs.twist &&
    lhs.distance_left == rhs.distance_left &&
    lhs.distance_right == rhs.distance_right &&
    lhs.linear_velocity == rhs.linear_velocity &&
    lhs.angular_velocity == rhs.angular_velocity &&
    lhs.imu_yaw == rhs.imu_yaw &&
    lhs.fused_yaw == rhs.fused_yaw &&
    lhs.yaw_confidence == rhs.yaw_confidence &&
    lhs.is_slipping == rhs.is_slipping &&
    lhs.slip_ratio == rhs.slip_ratio &&
    lhs.encoder_errors == rhs.encoder_errors;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_car_yolo::OdometryProcessed_<ContainerAllocator1> & lhs, const ::my_car_yolo::OdometryProcessed_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_car_yolo

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::my_car_yolo::OdometryProcessed_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_car_yolo::OdometryProcessed_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_car_yolo::OdometryProcessed_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_car_yolo::OdometryProcessed_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_car_yolo::OdometryProcessed_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_car_yolo::OdometryProcessed_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_car_yolo::OdometryProcessed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0a93869a001531267c92fa7909c7c4ce";
  }

  static const char* value(const ::my_car_yolo::OdometryProcessed_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0a93869a00153126ULL;
  static const uint64_t static_value2 = 0x7c92fa7909c7c4ceULL;
};

template<class ContainerAllocator>
struct DataType< ::my_car_yolo::OdometryProcessed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_car_yolo/OdometryProcessed";
  }

  static const char* value(const ::my_car_yolo::OdometryProcessed_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_car_yolo::OdometryProcessed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# 处理后的里程计数据消息\n"
"# 包含运动学模型、航迹推演、IMU融合结果\n"
"\n"
"std_msgs/Header header\n"
"string child_frame_id\n"
"\n"
"# 位姿估计 (世界坐标系)\n"
"geometry_msgs/PoseWithCovariance pose\n"
"\n"
"# 速度估计\n"
"geometry_msgs/TwistWithCovariance twist\n"
"\n"
"# 里程计特有字段\n"
"float64 distance_left    # 左轮行驶距离 (米)\n"
"float64 distance_right   # 右轮行驶距离 (米)\n"
"\n"
"# 运动学参数\n"
"float64 linear_velocity  # 当前线速度 (m/s)\n"
"float64 angular_velocity # 当前角速度 (rad/s)\n"
"\n"
"# IMU融合相关\n"
"float64 imu_yaw          # IMU航向角 (用于融合)\n"
"float64 fused_yaw        # IMU+编码器融合航向角\n"
"float64 yaw_confidence   # 航向角置信度 (0-1)\n"
"\n"
"# 状态标志\n"
"bool is_slipping         # 是否检测到打滑\n"
"float64 slip_ratio       # 打滑比例 (0-1)\n"
"uint32 encoder_errors    # 编码器错误计数\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseWithCovariance\n"
"# This represents a pose in free space with uncertainty.\n"
"\n"
"Pose pose\n"
"\n"
"# Row-major representation of the 6x6 covariance matrix\n"
"# The orientation parameters use a fixed-axis representation.\n"
"# In order, the parameters are:\n"
"# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)\n"
"float64[36] covariance\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/TwistWithCovariance\n"
"# This expresses velocity in free space with uncertainty.\n"
"\n"
"Twist twist\n"
"\n"
"# Row-major representation of the 6x6 covariance matrix\n"
"# The orientation parameters use a fixed-axis representation.\n"
"# In order, the parameters are:\n"
"# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)\n"
"float64[36] covariance\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Twist\n"
"# This expresses velocity in free space broken into its linear and angular parts.\n"
"Vector3 linear\n"
"Vector3 angular\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::my_car_yolo::OdometryProcessed_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_car_yolo::OdometryProcessed_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.child_frame_id);
      stream.next(m.pose);
      stream.next(m.twist);
      stream.next(m.distance_left);
      stream.next(m.distance_right);
      stream.next(m.linear_velocity);
      stream.next(m.angular_velocity);
      stream.next(m.imu_yaw);
      stream.next(m.fused_yaw);
      stream.next(m.yaw_confidence);
      stream.next(m.is_slipping);
      stream.next(m.slip_ratio);
      stream.next(m.encoder_errors);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct OdometryProcessed_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_car_yolo::OdometryProcessed_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_car_yolo::OdometryProcessed_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "child_frame_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.child_frame_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "pose: ";
    Printer< ::geometry_msgs::PoseWithCovariance_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "twist: ";
    Printer< ::geometry_msgs::TwistWithCovariance_<ContainerAllocator> >::stream(s, indent + "  ", v.twist);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "distance_left: ";
    Printer<double>::stream(s, indent + "  ", v.distance_left);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "distance_right: ";
    Printer<double>::stream(s, indent + "  ", v.distance_right);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "linear_velocity: ";
    Printer<double>::stream(s, indent + "  ", v.linear_velocity);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "angular_velocity: ";
    Printer<double>::stream(s, indent + "  ", v.angular_velocity);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "imu_yaw: ";
    Printer<double>::stream(s, indent + "  ", v.imu_yaw);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "fused_yaw: ";
    Printer<double>::stream(s, indent + "  ", v.fused_yaw);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "yaw_confidence: ";
    Printer<double>::stream(s, indent + "  ", v.yaw_confidence);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "is_slipping: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_slipping);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "slip_ratio: ";
    Printer<double>::stream(s, indent + "  ", v.slip_ratio);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "encoder_errors: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.encoder_errors);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_CAR_YOLO_MESSAGE_ODOMETRYPROCESSED_H
