// Generated by gencpp from file my_car_yolo/WheelEncoders.msg
// DO NOT EDIT!


#ifndef MY_CAR_YOLO_MESSAGE_WHEELENCODERS_H
#define MY_CAR_YOLO_MESSAGE_WHEELENCODERS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace my_car_yolo
{
template <class ContainerAllocator>
struct WheelEncoders_
{
  typedef WheelEncoders_<ContainerAllocator> Type;

  WheelEncoders_()
    : header()
    , left_pulses(0)
    , right_pulses(0)
    , left_velocity(0.0)
    , right_velocity(0.0)  {
    }
  WheelEncoders_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , left_pulses(0)
    , right_pulses(0)
    , left_velocity(0.0)
    , right_velocity(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _left_pulses_type;
  _left_pulses_type left_pulses;

   typedef int32_t _right_pulses_type;
  _right_pulses_type right_pulses;

   typedef double _left_velocity_type;
  _left_velocity_type left_velocity;

   typedef double _right_velocity_type;
  _right_velocity_type right_velocity;





  typedef boost::shared_ptr< ::my_car_yolo::WheelEncoders_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_car_yolo::WheelEncoders_<ContainerAllocator> const> ConstPtr;

}; // struct WheelEncoders_

typedef ::my_car_yolo::WheelEncoders_<std::allocator<void> > WheelEncoders;

typedef boost::shared_ptr< ::my_car_yolo::WheelEncoders > WheelEncodersPtr;
typedef boost::shared_ptr< ::my_car_yolo::WheelEncoders const> WheelEncodersConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_car_yolo::WheelEncoders_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_car_yolo::WheelEncoders_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_car_yolo::WheelEncoders_<ContainerAllocator1> & lhs, const ::my_car_yolo::WheelEncoders_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.left_pulses == rhs.left_pulses &&
    lhs.right_pulses == rhs.right_pulses &&
    lhs.left_velocity == rhs.left_velocity &&
    lhs.right_velocity == rhs.right_velocity;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_car_yolo::WheelEncoders_<ContainerAllocator1> & lhs, const ::my_car_yolo::WheelEncoders_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_car_yolo

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::my_car_yolo::WheelEncoders_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_car_yolo::WheelEncoders_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_car_yolo::WheelEncoders_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_car_yolo::WheelEncoders_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_car_yolo::WheelEncoders_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_car_yolo::WheelEncoders_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_car_yolo::WheelEncoders_<ContainerAllocator> >
{
  static const char* value()
  {
    return "04b36400bf0a0e74c73173ddcaa70f42";
  }

  static const char* value(const ::my_car_yolo::WheelEncoders_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x04b36400bf0a0e74ULL;
  static const uint64_t static_value2 = 0xc73173ddcaa70f42ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_car_yolo::WheelEncoders_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_car_yolo/WheelEncoders";
  }

  static const char* value(const ::my_car_yolo::WheelEncoders_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_car_yolo::WheelEncoders_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# WheelEncoders.msg\n"
"# 轮子编码器原始数据\n"
"\n"
"std_msgs/Header header\n"
"int32 left_pulses              # 左轮编码器脉冲数\n"
"int32 right_pulses             # 右轮编码器脉冲数\n"
"float64 left_velocity          # 左轮速度 (m/s)\n"
"float64 right_velocity         # 右轮速度 (m/s)\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::my_car_yolo::WheelEncoders_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_car_yolo::WheelEncoders_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.left_pulses);
      stream.next(m.right_pulses);
      stream.next(m.left_velocity);
      stream.next(m.right_velocity);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WheelEncoders_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_car_yolo::WheelEncoders_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_car_yolo::WheelEncoders_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "left_pulses: ";
    Printer<int32_t>::stream(s, indent + "  ", v.left_pulses);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "right_pulses: ";
    Printer<int32_t>::stream(s, indent + "  ", v.right_pulses);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "left_velocity: ";
    Printer<double>::stream(s, indent + "  ", v.left_velocity);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "right_velocity: ";
    Printer<double>::stream(s, indent + "  ", v.right_velocity);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_CAR_YOLO_MESSAGE_WHEELENCODERS_H
